/*
 * Copyright (c) 2026 ThorVG project. All rights reserved.

 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:

 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "tvgBgfxContext.h"

// bgfx::EmbeddedShader / bgfx::createEmbeddedShader / BGFX_EMBEDDED_SHADER 定义
// 在独立头文件中，bgfx.h 本身不提供
#include <bgfx/embedded_shader.h>

/*
 * Embedded shaders are generated by shaders/compile_shaders.py (bgfx shaderc)
 * into the *.bin.h files referenced below. Until they are generated the
 * backend logs an error on program creation instead of failing to compile.
 */
// The sentinel requires every shader header: compile_shaders.py generates them
// as an atomic set, so a partial collection means generation is incomplete and
// the embedded path must stay off (runtime falls back to the TVGERR below).
#if defined(__has_include)
    #if __has_include("vs_shape.bin.h")  && \
        __has_include("fs_solid.bin.h")  && \
        __has_include("fs_gradient.bin.h") && \
        __has_include("fs_image.bin.h")  && \
        __has_include("fs_blit.bin.h")   && \
        __has_include("fs_blur.bin.h")   && \
        __has_include("fs_effect.bin.h")
        #define TVG_BGFX_SHADERS_EMBEDDED 1
        #include "vs_shape.bin.h"
        #include "fs_solid.bin.h"
        #include "fs_gradient.bin.h"
        #include "fs_image.bin.h"
        #include "fs_blit.bin.h"
        #include "fs_blur.bin.h"
        #include "fs_effect.bin.h"
    #endif
#endif

namespace
{
// names must stay in sync with the .sc shader sources (checked by
// tools/check_bgfx_backend.py --uniforms)
constexpr const char* UNIFORM_NAMES[] = {
    "u_viewportMatrix",
    "u_depth",
    "u_paintMatrix",
    "u_color",
    "u_gradient",
    "u_blit",
    "u_blur",
    "u_effect",
    "s_ramp",
    "s_tex",
    "s_mask",
    "s_dst",
};

constexpr const char* PROGRAM_SHADER_NAMES[] = {
    "fs_solid",
    "fs_gradient",
    "fs_image",
    "fs_blit",
    "fs_blur",
    "fs_effect",
};

#ifdef TVG_BGFX_SHADERS_EMBEDDED
const bgfx::EmbeddedShader s_embeddedShaders[] = {
    BGFX_EMBEDDED_SHADER(vs_shape),
    BGFX_EMBEDDED_SHADER(fs_solid),
    BGFX_EMBEDDED_SHADER(fs_gradient),
    BGFX_EMBEDDED_SHADER(fs_image),
    BGFX_EMBEDDED_SHADER(fs_blit),
    BGFX_EMBEDDED_SHADER(fs_blur),
    BGFX_EMBEDDED_SHADER(fs_effect),
    BGFX_EMBEDDED_SHADER_END()
};
#endif

}  // namespace


bool BgfxContext::initialize(uint16_t base, uint16_t count)
{
    if (mInitialized) return true;
    if (!bgfx::getCaps()) {
        TVGERR("BGFX_ENGINE", "bgfx is not initialized. Call bgfx::init() before using BgfxCanvas.");
        return false;
    }

    viewBase = base;
    viewCount = count;
    viewNext = base;

    // uniforms are created eagerly; samplers share the creation path
    const bgfx::UniformType::Enum types[uint8_t(BgfxUniform::Count)] = {
        bgfx::UniformType::Mat4,    // u_viewportMatrix
        bgfx::UniformType::Vec4,    // u_depth
        bgfx::UniformType::Mat4,    // u_paintMatrix
        bgfx::UniformType::Vec4,    // u_color
        bgfx::UniformType::Vec4,    // u_gradient (num = 2)
        bgfx::UniformType::Vec4,    // u_blit
        bgfx::UniformType::Vec4,    // u_blur
        bgfx::UniformType::Vec4,    // u_effect (num = 3)
        bgfx::UniformType::Sampler, // s_ramp
        bgfx::UniformType::Sampler, // s_tex
        bgfx::UniformType::Sampler, // s_mask
        bgfx::UniformType::Sampler, // s_dst
    };
    const uint16_t nums[uint8_t(BgfxUniform::Count)] = {1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 1};

    for (uint8_t i = 0; i < uint8_t(BgfxUniform::Count); ++i) {
        mUniforms[i] = bgfx::createUniform(UNIFORM_NAMES[i], types[i], nums[i]);
    }

    mInitialized = true;
    return true;
}


bool BgfxContext::createShaders()
{
#ifdef TVG_BGFX_SHADERS_EMBEDDED
    auto rendererType = bgfx::getRendererType();

    auto vertex = bgfx::createEmbeddedShader(s_embeddedShaders, rendererType, "vs_shape");
    if (!bgfx::isValid(vertex)) {
        TVGERR("BGFX_ENGINE", "failed to load embedded vertex shader 'vs_shape' for renderer %d", rendererType);
        return false;
    }

    for (uint8_t i = 0; i < uint8_t(BgfxProgram::Count); ++i) {
        auto fragment = bgfx::createEmbeddedShader(s_embeddedShaders, rendererType, PROGRAM_SHADER_NAMES[i]);
        if (!bgfx::isValid(fragment)) {
            TVGERR("BGFX_ENGINE", "failed to load embedded fragment shader '%s' for renderer %d", PROGRAM_SHADER_NAMES[i], rendererType);
            bgfx::destroy(vertex);
            return false;
        }
        // 6 个 program 共享同一个 vertex shader：_destroyShaders 必须为 false，
        // 否则首个 program 销毁时会带走 vertex shader，其余 program 变成悬垂引用。
        // program 自身持有 shader 引用（incRef），这里立即释放创建者的引用即可。
        mPrograms[i] = bgfx::createProgram(vertex, fragment, false);
        bgfx::destroy(fragment);
        if (!bgfx::isValid(mPrograms[i])) {
            TVGERR("BGFX_ENGINE", "failed to create program '%s'", PROGRAM_SHADER_NAMES[i]);
        }
    }
    bgfx::destroy(vertex);
    return true;
#else
    TVGERR("BGFX_ENGINE", "embedded shaders are missing. Generate them with: python third_party/thorvg/src/renderer/gpu_engine/bgfx/shaders/compile_shaders.py");
    return false;
#endif
}


bgfx::ProgramHandle BgfxContext::program(BgfxProgram id)
{
    auto& handle = mPrograms[uint8_t(id)];
    if (!bgfx::isValid(handle)) createShaders();
    return handle;
}


void BgfxContext::setupView(uint16_t view, bgfx::FrameBufferHandle fb, uint16_t w, uint16_t h, bool clear, uint32_t rgba)
{
    // Draw calls MUST execute in submission order: the stencil-and-cover fill
    // relies on each shape's "winding" pass being immediately followed by its
    // "cover" pass. bgfx's default view mode (SortKey::SortProgram, see
    // SortKey::encodeDraw) reorders submits by program index BEFORE depth, so a
    // gradient cover (Gradient program) would be pulled behind every later
    // Solid winding pass -- the windings of all shapes would run first, the
    // earlier cover would then repaint the whole stencil while zeroing it, and
    // every following cover would find an all-zero stencil and draw nothing.
    bgfx::setViewMode(view, bgfx::ViewMode::Sequential);
    bgfx::setViewRect(view, 0, 0, w, h);
    if (bgfx::isValid(fb)) bgfx::setViewFrameBuffer(view, fb);
    if (clear) {
        bgfx::setViewClear(view, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH | BGFX_CLEAR_STENCIL, rgba, BGFX_CLIP_DEPTH_BASE, 0);
    }
    // touches the view even without clear, so the bgfx frame graph keeps it alive
    bgfx::touch(view);
}


void BgfxContext::release()
{
    if (!mInitialized) return;

    for (auto&& program : mPrograms) {
        if (bgfx::isValid(program)) bgfx::destroy(program);
        program = BGFX_INVALID_HANDLE;
    }
    for (auto&& uniform : mUniforms) {
        if (bgfx::isValid(uniform)) bgfx::destroy(uniform);
        uniform = BGFX_INVALID_HANDLE;
    }

    mInitialized = false;
}
